;AUTORES: Alex Tomé Aguir e Irene Ruiz Juez
;FECHA:08/05/2019
;DESCRIPCION:PROGRAMA AL PULSAR EN UNA DE LAS TECLAS DEL SIMULADOR, DICHA TECLA
;SEA REPRESNTADA EN EL DISPLAY
;B REPRESENTA LA TECLA PULSADA

	.ORG 1000H	
	MVI A,08H	;Activa el bit MSE
	SIM		;Fijamos la máscara
BUCLE:
	RIM		;Carga la máscara
	ANI 16		;HHacemos un AND con 16
	CPI 16		;Comparamos con 16
	JNZ BUCLE	;Vamos al bucle 
	CALL 044EH	;Llamamos la subrutina
	MOV B,A		;Movemos el contenido del REG.A AL REG.B
	CALL 04D5H	;Llamamos a la subrutina 04D5H
	EI		;HABILITA LAS INTERRUPCIONES
	MOV A,B		;Movemos el contenido del REG.B AL REG.A
	CPI 30H		;Compara A con 30
	JNZ BUCLE	;SALTAMOS A BUCLE 
	HLT		;FIN DEL PROGRAMA

;INTERRUPCION

	.ORG 002CH	
	RET		;DETENEMOS LA SUBRUTINA

;COGE EL DATO DEL TECLADO Y LO GUARDA EN AC

	.ORG 044EH	
	IN 0		;Pasa la señal del puerto 0 AL REG.A
	RET		;DETENENOS LA SUBRUTINA
	
;MOSTRAMOS POR PANTALLA EL DATO

	.ORG 04D5H	
	MOV B,A		;Pasamos el contenido del REG.A AL REG.B
	STA E1A0H	;ALMACENAMOS EL REG.A EN LA DIRECCION
	RET		;DETENEMOS LA SUBRUTINA